### ISSUE TITLE
Error Tambah Artikel

### ISSUE THREAD

**Issue by imamsutono** [pasuruandev/covid19#1]
mas @uddinmtm , ada error seperti yang terlampir di gambar pas aku tambah artikel.

mohon bantuannya, terima kasih

![error-add-article](https://user-images.githubusercontent.com/17371955/84261204-98a0f580-ab45-11ea-91e7-a3a05428e076.PNG)

**Comment by uddinmtm** [comment]
Hemm, sepertinya ada yang salah. 
Oke ta cek e

**Comment by imamsutono** [comment]
#2 solved, thanks mas
