### ISSUE TITLE
Label kecamatan selalu "Purwodadi"

### ISSUE THREAD

**Issue by imamsutono** [pasuruandev/covid19#17]
Halo tim,
Issue ini ada di dashboard -> map. Ketika klik salah satu kecamatan untuk edit, popup yang muncul selalu dengan judul "Persebaran Covid **Purwodadi**" meskipun aku klik kecamatan lain.

![issue-kec](https://user-images.githubusercontent.com/17371955/92835392-5cf81f00-f405-11ea-9363-7d1812ebbfbb.png)

![issue-covid-kecamatan](https://user-images.githubusercontent.com/17371955/92835546-916bdb00-f405-11ea-98a9-c04d70bdcefb.png)

Untuk issue ini bisa dihandle @adamaulana atau @ifanfairuz ya?

Terima kasih.

**Comment by ifanfairuz** [comment]
minta tolong di cek dulu mas @imamsutono di #19

**Comment by ifanfairuz** [comment]
minta tolong di review dulu mas @imamsutono di #19
